# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 3
# Issues with these labels will never be considered stale
exemptLabels:
  - wip
# Label to use when marking an issue as stale
staleLabel: invalid
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  由于太长时间没有得到回复本问题会自动被关闭，如果您还有问题可以重新开启或提交新问题。感谢你对于本 EFI 仓库的关注！
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
